# Generated by Django 5.2.16 on 2026-08-02 05:09

import django.db.models.deletion
import django.utils.timezone
import pinforge_web.uploads
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinforge_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(max_length=120)),
                ('primary', models.CharField(default='#173C35', max_length=7)),
                ('accent', models.CharField(default='#C9855B', max_length=7)),
                ('surface', models.CharField(default='#F4F0E6', max_length=7)),
                ('ink', models.CharField(default='#18201D', max_length=7)),
                ('headline_font', models.CharField(default='DejaVuSerif-Bold.ttf', max_length=64)),
                ('body_font', models.CharField(default='DejaVuSans.ttf', max_length=64)),
                ('body_bold_font', models.CharField(default='DejaVuSans-Bold.ttf', max_length=64)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_kit', to='pinforge_web.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_listing_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=500)),
                ('listing_url', models.URLField(max_length=2000)),
                ('price_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('tags', models.JSONField(default=list)),
                ('description', models.TextField(blank=True)),
                ('vertical', models.CharField(default='general', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('synchronized_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='pinforge_web.organization')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_id', models.CharField(choices=[('mockup_hero', 'Mockup Hero'), ('list_stack', 'List Stack'), ('split_compare', 'Split Compare'), ('text_overlay', 'Text Overlay'), ('grid_preview', 'Grid Preview')], max_length=32)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('alt_text', models.CharField(max_length=500)),
                ('destination_url', models.URLField(max_length=2000)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('input_revision', models.CharField(blank=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='pinforge_web.organization')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='pinforge_web.listing')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('etsy', 'Etsy')], max_length=16)),
                ('source_shop_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='pinforge_web.organization')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='pinforge_web.shop'),
        ),
        migrations.CreateModel(
            name='CreativeAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=500, upload_to=pinforge_web.uploads.creative_asset_upload_to)),
                ('mime_type', models.CharField(default='image/png', max_length=32)),
                ('byte_size', models.BigIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('creative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='pinforge_web.creative')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_assets', to='pinforge_web.organization')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('byte_size__gte', 0)), name='creative_asset_size_non_negative'), models.CheckConstraint(condition=models.Q(('height__gt', 0), ('width__gt', 0)), name='creative_asset_dimensions_positive')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('render_creative', 'Render creative')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('retry', 'Retry'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('priority', models.SmallIntegerField(default=100)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_owner', models.CharField(blank=True, max_length=128)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('deduplication_key', models.CharField(max_length=160)),
                ('result', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='pinforge_web.organization')),
            ],
            options={
                'ordering': ('priority', 'due_at', 'created_at', 'id'),
                'indexes': [models.Index(fields=['status', 'due_at', 'priority'], name='job_claim_order_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'kind', 'deduplication_key'), name='unique_job_deduplication_key'), models.CheckConstraint(condition=models.Q(('attempts__gte', 0)), name='job_attempts_non_negative'), models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='job_max_attempts_positive')],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=500, upload_to=pinforge_web.uploads.listing_image_upload_to)),
                ('position', models.PositiveSmallIntegerField()),
                ('mime_type', models.CharField(max_length=32)),
                ('byte_size', models.BigIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pinforge_web.listing')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_images', to='pinforge_web.organization')),
            ],
            options={
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('listing', 'position'), name='unique_listing_image_position'), models.CheckConstraint(condition=models.Q(('byte_size__gte', 0)), name='listing_image_size_non_negative'), models.CheckConstraint(condition=models.Q(('height__gt', 0), ('width__gt', 0)), name='listing_image_dimensions_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(fields=('organization', 'source', 'source_shop_id'), name='unique_shop_source_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('organization', 'shop', 'source_listing_id'), name='unique_listing_source_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('price_minor__gte', 0)), name='listing_price_minor_non_negative'),
        ),
    ]
