# Generated by Django 5.2.16 on 2026-08-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinforge_web', '0002_brandkit_listing_creative_shop_listing_shop_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='creative',
            constraint=models.UniqueConstraint(condition=models.Q(('input_revision', ''), _negated=True), fields=('organization', 'listing', 'input_revision'), name='unique_creative_input_revision'),
        ),
    ]
