# Generated by Django 5.2.17 on 2026-08-16 21:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinforge_web', '0003_creative_unique_creative_input_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('etsy', 'Etsy')], max_length=16)),
                ('external_account_id', models.CharField(max_length=128)),
                ('token_ciphertext', models.TextField()),
                ('scopes', models.JSONField(default=list)),
                ('token_expires_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_connections', to='pinforge_web.organization')),
            ],
            options={
                'ordering': ('provider', 'external_account_id', 'id'),
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_account_id'), name='unique_provider_account_connection')],
            },
        ),
    ]
