# Generated by Django 5.2.16 on 2026-08-16 23:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pinforge_web", "0004_providerconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shops",
                to="pinforge_web.providerconnection",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="kind",
            field=models.CharField(
                choices=[
                    ("render_creative", "Render creative"),
                    ("sync_etsy", "Sync Etsy listings"),
                    ("publish_pinterest", "Publish to Pinterest"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="providerconnection",
            name="provider",
            field=models.CharField(
                choices=[("etsy", "Etsy"), ("pinterest", "Pinterest")], max_length=16
            ),
        ),
        migrations.CreateModel(
            name="PinterestBoard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_board_id", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("active", models.BooleanField(default=True)),
                (
                    "synchronized_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinterest_boards",
                        to="pinforge_web.providerconnection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinterest_boards",
                        to="pinforge_web.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="PinPublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("publish_unknown", "Needs review"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("remote_pin_id", models.CharField(blank=True, max_length=128)),
                ("remote_url", models.URLField(blank=True, max_length=2000)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pin_publications",
                        to="pinforge_web.providerconnection",
                    ),
                ),
                (
                    "creative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="pinforge_web.creative",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_publications",
                        to="pinforge_web.organization",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pin_publications",
                        to="pinforge_web.pinterestboard",
                    ),
                ),
            ],
            options={
                "ordering": ("-scheduled_at", "-created_at", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="pinterestboard",
            constraint=models.UniqueConstraint(
                fields=("connection", "external_board_id"),
                name="unique_pinterest_board_per_connection",
            ),
        ),
    ]
